# Generated by Django 4.1.5 on 2023-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating_all',
            field=models.IntegerField(default=0),
        ),
    ]
