# Generated by Django 4.1.5 on 2023-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_author_rating_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], default='Новость', max_length=255),
        ),
    ]
