# Generated by Django 4.1.5 on 2023-02-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_alter_post_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_all',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating_comment',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating_comment_post',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating_post',
        ),
    ]
