# Generated by Django 4.1.5 on 2023-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_rename_rating_all_author_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(),
        ),
    ]
